### ISSUE TITLE
List of activity types (sport_type) not complete

### ISSUE THREAD

**Issue by piposys** [qgriffith/strava-client-rs#6]
Dear Quenten,

Thanks for Strava Client RS!

I'm currently actively using it and discovered that multiple sport_types are not foreseen in the ActivityType enum, e.g. GravelRide and VirtualRide. I locally added those and now these two are returned correctly.

The full list of activities can be found here: https://support.strava.com/hc/en-us/articles/216919407-Supported-Sport-Types-on-Strava
e.g. Mountain Bike Ride will be returned as MountainBikeRide by the API.

Just let me know: will you add them in a new version or do I make the modifications in a fork?

**Comment by qgriffith** [comment]
You can open a PR to add them or I can do it early next week. Thanks for
the list of activities.

**Comment by qgriffith** [comment]
PR up!

**Comment by qgriffith** [comment]
A new version has been released https://crates.io/crates/strava-client-rs
